local c = require('config.design').c

return {
	Normal = { fg = c.fg, bg = c.bg, },
	NormalFloat = { fg = c.fg, bg = c.bg, },
	Comment = { fg = c.comment, },
	Constant = { fg = c.yellow, },
	String = { fg = c.yellow, },
	Character = { fg = c.green, },
	Number = { fg = c.orange, },
	Boolean = { fg = c.cyan, },
	Float = { fg = c.orange, },
	FloatBorder = { fg = c.white, },
	Operator = { fg = c.purple, },
	Keyword = { fg = c.cyan, },
	Keywords = { fg = c.cyan, },
	Identifier = { fg = c.cyan, },
	Function = { fg = c.yellow, },
	Statement = { fg = c.purple, },
	Conditional = { fg = c.pink, },
	Repeat = { fg = c.pink, },
	Label = { fg = c.cyan, },
	Exception = { fg = c.purple, },
	PreProc = { fg = c.yellow, },
	Include = { fg = c.purple, },
	Define = { fg = c.purple, },
	Title = { fg = c.cyan, },
	Macro = { fg = c.purple, },
	PreCondit = { fg = c.cyan, },
	Type = { fg = c.cyan, },
	StorageClass = { fg = c.pink, },
	Structure = { fg = c.yellow, },
	TypeDef = { fg = c.yellow, },
	Special = { fg = c.green, italic = true },
	SpecialComment = { fg = c.comment, italic = true, },
	Error = { fg = c.bright_red, },
	Todo = { fg = c.purple, bold = true, italic = true, },
	Underlined = { fg = c.cyan, underline = true, },

	Cursor = { reverse = true, },
	CursorLineNr = { fg = c.fg, bold = true, },

	SignColumn = { bg = c.bg, },

	Conceal = { fg = c.comment, },
	CursorColumn = { bg = c.black, },
	CursorLine = { bg = c.selection, },
	ColorColumn = { bg = c.selection, },

	StatusLine = { fg = c.white, bg = c.black, },
	StatusLineNC = { fg = c.comment, },
	StatusLineTerm = { fg = c.white, bg = c.black, },
	StatusLineTermNC = { fg = c.comment, },

	Directory = { fg = c.cyan, },
	DiffAdd = { fg = c.bg, bg = c.green, },
	DiffChange = { fg = c.orange, },
	DiffDelete = { fg = c.red, },
	DiffText = { fg = c.comment, },

	ErrorMsg = { fg = c.bright_red, },
	VertSplit = { fg = c.black, },
	Folded = { fg = c.comment, },
	FoldColumn = {},
	Search = { fg = c.black, bg = c.orange, },
	IncSearch = { fg = c.orange, bg = c.comment, },
	LineNr = { fg = c.comment, },
	MatchParen = { fg = c.fg, underline = true, },
	NonText = { fg = c.nontext, },
	Pmenu = { fg = c.white, bg = c.menu, },
	PmenuSel = { fg = c.white, bg = c.selection, },
	PmenuSbar = { bg = c.bg, },
	PmenuThumb = { bg = c.selection, },

	Question = { fg = c.purple, },
	QuickFixLine = { fg = c.black, bg = c.yellow, },
	SpecialKey = { fg = c.nontext, },

	SpellBad = { fg = c.bright_red, underline = true, },
	SpellCap = { fg = c.yellow, },
	SpellLocal = { fg = c.yellow, },
	SpellRare = { fg = c.yellow, },

	TabLine = { fg = c.comment, },
	TabLineSel = { fg = c.white, },
	TabLineFill = { bg = c.bg, },
	Terminal = { fg = c.white, bg = c.black, },
	Visual = { bg = c.visual, },
	VisualNOS = { fg = c.visual, },
	WarningMsg = { fg = c.yellow, },
	WildMenu = { fg = c.black, bg = c.white, },

	-- TreeSitter
	['@error'] = { fg = c.bright_red, },
	['@punctuation.delimiter'] = { fg = c.fg, },
	['@punctuation.bracket'] = { fg = c.fg, },
	['@punctuation.special'] = { fg = c.cyan, },

	['@constant'] = { fg = c.purple, },
	['@constant.builtin'] = { fg = c.purple, },
	['@symbol'] = { fg = c.purple, },

	['@constant.macro'] = { fg = c.cyan, },
	['@string.regex'] = { fg = c.red, },
	['@string'] = { fg = c.yellow, },
	['@string.escape'] = { fg = c.cyan, },
	['@character'] = { fg = c.green, },
	['@number'] = { fg = c.purple, },
	['@boolean'] = { fg = c.purple, },
	['@float'] = { fg = c.green, },
	['@annotation'] = { fg = c.yellow, },
	['@attribute'] = { fg = c.cyan, },
	['@namespace'] = { fg = c.orange, },

	['@function.builtin'] = { fg = c.cyan, },
	['@function'] = { fg = c.green, },
	['@function.macro'] = { fg = c.green, },
	['@parameter'] = { fg = c.orange, },
	['@parameter.reference'] = { fg = c.orange, },
	['@method'] = { fg = c.green, },
	['@field'] = { fg = c.orange, },
	['@property'] = { fg = c.purple, },
	['@constructor'] = { fg = c.cyan, },

	['@conditional'] = { fg = c.pink, },
	['@repeat'] = { fg = c.pink, },
	['@label'] = { fg = c.cyan, },

	['@keyword'] = { fg = c.pink, },
	['@keyword.function'] = { fg = c.cyan, },
	['@keyword.operator'] = { fg = c.pink, },
	['@operator'] = { fg = c.pink, },
	['@exception'] = { fg = c.purple, },
	['@type'] = { fg = c.bright_cyan, },
	['@type.builtin'] = { fg = c.cyan, italic = true, },
	['@type.qualifier'] = { fg = c.pink, },
	['@structure'] = { fg = c.purple, },
	['@include'] = { fg = c.pink, },

	['@variable'] = { fg = c.fg, },
	['@variable.builtin'] = { fg = c.purple, },

	['@text'] = { fg = c.orange, },
	['@text.strong'] = { fg = c.orange, bold = true, }, -- bold
	['@text.emphasis'] = { fg = c.yellow, italic = true, }, -- italic
	['@text.underline'] = { fg = c.orange, },
	['@text.title'] = { fg = c.pink, bold = true, }, -- title
	['@text.literal'] = { fg = c.yellow, }, -- inline code
	['@text.uri'] = { fg = c.yellow, italic = true, }, -- urls
	['@text.reference'] = { fg = c.orange, bold = true, },

	['@tag'] = { fg = c.cyan, },
	['@tag.attribute'] = { fg = c.green, },
	['@tag.delimiter'] = { fg = c.cyan, },

	  -- Semantic
	['@class'] = { fg = c.cyan },
	['@struct'] = { fg = c.cyan },
	['@enum'] = { fg = c.cyan },
	['@enumMember'] = { fg = c.purple },
	['@event'] = { fg = c.cyan },
	['@interface'] = { fg = c.cyan },
	['@modifier'] = { fg = c.cyan },
	['@regexp'] = { fg = c.yellow },
	['@typeParameter'] = { fg = c.cyan },
	['@decorator'] = { fg = c.cyan },

	-- HTML
	htmlArg = { fg = c.green, },
	htmlBold = { fg = c.yellow, bold = true, },
	htmlEndTag = { fg = c.cyan, },
	htmlH1 = { fg = c.pink, },
	htmlH2 = { fg = c.pink, },
	htmlH3 = { fg = c.pink, },
	htmlH4 = { fg = c.pink, },
	htmlH5 = { fg = c.pink, },
	htmlH6 = { fg = c.pink, },
	htmlItalic = { fg = c.purple, italic = true, },
	htmlLink = { fg = c.purple, underline = true, },
	htmlSpecialChar = { fg = c.yellow, },
	htmlSpecialTagName = { fg = c.cyan, },
	htmlTag = { fg = c.cyan, },
	htmlTagN = { fg = c.cyan, },
	htmlTagName = { fg = c.cyan, },
	htmlTitle = { fg = c.white, },

	-- Markdown
	markdownBlockquote = { fg = c.yellow, italic = true, },
	markdownBold = { fg = c.orange, bold = true, },
	markdownCode = { fg = c.green, },
	markdownCodeBlock = { fg = c.orange, },
	markdownCodeDelimiter = { fg = c.red, },
	markdownH1 = { fg = c.pink, bold = true, },
	markdownH2 = { fg = c.pink, bold = true, },
	markdownH3 = { fg = c.pink, bold = true, },
	markdownH4 = { fg = c.pink, bold = true, },
	markdownH5 = { fg = c.pink, bold = true, },
	markdownH6 = { fg = c.pink, bold = true, },
	markdownHeadingDelimiter = { fg = c.red, },
	markdownHeadingRule = { fg = c.comment, },
	markdownId = { fg = c.purple, },
	markdownIdDeclaration = { fg = c.cyan, },
	markdownIdDelimiter = { fg = c.purple, },
	markdownItalic = { fg = c.yellow, italic = true, },
	markdownLinkDelimiter = { fg = c.purple, },
	markdownLinkText = { fg = c.pink, },
	markdownListMarker = { fg = c.cyan, },
	markdownOrderedListMarker = { fg = c.red, },
	markdownRule = { fg = c.comment, },

	--  Diff
	diffAdded = { fg = c.green, },
	diffRemoved = { fg = c.red, },
	diffFileId = { fg = c.yellow, bold = true, reverse = true, },
	diffFile = { fg = c.nontext, },
	diffNewFile = { fg = c.green, },
	diffOldFile = { fg = c.red, },

	debugPc = { bg = c.cyan, },
	debugBreakpoint = { fg = c.red, reverse = true, },

	-- Git Signs
	GitSignsAdd = { fg = c.bright_green, },
	GitSignsChange = { fg = c.cyan, },
	GitSignsDelete = { fg = c.bright_red, },
	GitSignsAddLn = { fg = c.black, bg = c.bright_green, },
	GitSignsChangeLn = { fg = c.black, bg = c.cyan, },
	GitSignsDeleteLn = { fg = c.black, bg = c.bright_red, },
	GitSignsCurrentLineBlame = { fg = c.white, },

	-- Telescope
	TelescopePromptBorder = { fg = c.comment, },
	TelescopeResultsBorder = { fg = c.comment, },
	TelescopePreviewBorder = { fg = c.comment, },
	TelescopeSelection = { fg = c.white, bg = c.selection, },
	TelescopeMultiSelection = { fg = c.purple, bg = c.selection, },
	TelescopeNormal = { fg = c.fg, bg = c.bg, },
	TelescopeMatching = { fg = c.green, },
	TelescopePromptPrefix = { fg = c.purple, },

	-- -- NvimTree
	-- NvimTreeNormal = { fg = c.fg, bg = c.menu, },
	-- NvimTreeVertSplit = { fg = c.bg, bg = c.bg, },
	-- NvimTreeRootFolder = { fg = c.fg, bold = true, },
	-- NvimTreeGitDirty = { fg = c.yellow, },
	-- NvimTreeGitNew = { fg = c.bright_green, },
	-- NvimTreeImageFile = { fg = c.pink, },
	-- NvimTreeFolderIcon = { fg = c.purple, },
	-- NvimTreeIndentMarker = { fg = c.nontext, },
	-- NvimTreeEmptyFolderName = { fg = c.comment, },
	-- NvimTreeFolderName = { fg = c.fg, },
	-- NvimTreeSpecialFile = { fg = c.pink, underline = true, },
	-- NvimTreeOpenedFolderName = { fg = c.fg, },
	-- NvimTreeCursorLine = { bg = c.selection, },
	-- NvimTreeIn = { bg = c.selection, },

	-- -- NeoTree
	-- NeoTreeNormal = { fg = c.fg, bg = c.menu, },
	-- NeoTreeNormalNC = { fg = c.fg, bg = c.menu, },
	-- NeoTreeDirectoryName = { fg = c.fg },
	-- NeoTreeGitUnstaged = { fg = c.bright_magenta },
	-- NeoTreeGitModified = { fg = c.bright_magenta },
	-- NeoTreeGitUntracked = { fg = c.bright_green },
	-- NeoTreeDirectoryIcon = { fg = c.purple },
	-- NeoTreeIndentMarker = { fg = c.nontext },
	-- NeoTreeDotfile = { fg = c.comment },

	-- LSP
	DiagnosticError = { fg = c.red, },
	DiagnosticWarn = { fg = c.yellow, },
	DiagnosticInfo = { fg = c.cyan, },
	DiagnosticHint = { fg = c.cyan, },
	DiagnosticUnderlineError = { undercurl = true, sp = c.red, },
	DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow, },
	DiagnosticUnderlineInfo = { undercurl = true, sp = c.cyan, },
	DiagnosticUnderlineHint = { undercurl = true, sp = c.cyan, },
	DiagnosticSignError = { fg = c.red, },
	DiagnosticSignWarn = { fg = c.yellow, },
	DiagnosticSignInfo = { fg = c.cyan, },
	DiagnosticSignHint = { fg = c.cyan, },
	DiagnosticFloatingError = { fg = c.red, },
	DiagnosticFloatingWarn = { fg = c.yellow, },
	DiagnosticFloatingInfo = { fg = c.cyan, },
	DiagnosticFloatingHint = { fg = c.cyan, },
	DiagnosticVirtualTextError = { fg = c.red, },
	DiagnosticVirtualTextWarn = { fg = c.yellow, },
	DiagnosticVirtualTextInfo = { fg = c.cyan, },
	DiagnosticVirtualTextHint = { fg = c.cyan, },

	LspDiagnosticsDefaultError = { fg = c.red, },
	LspDiagnosticsDefaultWarning = { fg = c.yellow, },
	LspDiagnosticsDefaultInformation = { fg = c.cyan, },
	LspDiagnosticsDefaultHint = { fg = c.cyan, },
	LspDiagnosticsUnderlineError = { fg = c.red, undercurl = true, },
	LspDiagnosticsUnderlineWarning = { fg = c.yellow, undercurl = true, },
	LspDiagnosticsUnderlineInformation = { fg = c.cyan, undercurl = true, },
	LspDiagnosticsUnderlineHint = { fg = c.cyan, undercurl = true, },
	LspReferenceText = { fg = c.orange, },
	LspReferenceRead = { fg = c.orange, },
	LspReferenceWrite = { fg = c.orange, },

	--LSP Saga
	LspFloatWinNormal = { fg = c.fg, },
	LspFloatWinBorder = { fg = c.comment, },
	LspSagaHoverBorder = { fg = c.comment, },
	LspSagaSignatureHelpBorder = { fg = c.comment, },
	LspSagaCodeActionBorder = { fg = c.comment, },
	LspSagaDefPreviewBorder = { fg = c.comment, },
	LspLinesDiagBorder = { fg = c.comment, },
	LspSagaRenameBorder = { fg = c.comment, },
	LspSagaBorderTitle = { fg = c.menu, },
	LSPSagaDiagnosticTruncateLine = { fg = c.comment, },
	LspSagaDiagnosticBorder = { fg = c.comment, },
	LspSagaShTruncateLine = { fg = c.comment, },
	LspSagaDocTruncateLine = { fg = c.comment, },
	LspSagaLspFinderBorder = { fg = c.comment, },

	-- IndentBlankLine
	IndentBlanklineContextChar = { fg = c.bright_red, nocombine = true, },

	-- Cmp
	CmpItemKind = { link = "Pmenu" },
	CmpItemAbbr = { link = "Pmenu" },
	CmpItemKindMethod = { link = "@method" },
	CmpItemKindText = { link = "@text" },
	CmpItemKindFunction = { link = "@function" },
	CmpItemKindConstructor = { link = "@type" },
	CmpItemKindVariable = { link = "@variable" },
	CmpItemKindClass = { link = "@type" },
	CmpItemKindInterface = { link = "@type" },
	CmpItemKindModule = { link = "@namespace" },
	CmpItemKindProperty = { link = "@property" },
	CmpItemKindOperator = { link = "@operator" },
	CmpItemKindReference = { link = "@parameter.reference" },
	CmpItemKindUnit = { link = "@field" },
	CmpItemKindValue = { link = "@field" },
	CmpItemKindField = { link = "@field" },
	CmpItemKindEnum = { link = "@field" },
	CmpItemKindKeyword = { link = "@keyword" },
	CmpItemKindSnippet = { link = "@text" },
	CmpItemKindColor = { link = "DevIconCss" },
	CmpItemKindFile = { link = "TSURI" },
	CmpItemKindFolder = { link = "TSURI" },
	CmpItemKindEvent = { link = "@constant" },
	CmpItemKindEnumMember = { link = "@field" },
	CmpItemKindConstant = { link = "@constant" },
	CmpItemKindStruct = { link = "@structure" },
	CmpItemKindTypeParameter = { link = "@parameter" },

	-- TS rainbow c
	rainbowcol1 = { fg = c.red, },
	rainbowcol2 = { fg = c.green, },
	rainbowcol3 = { fg = c.yellow, },
	rainbowcol4 = { fg = c.purple, },
	rainbowcol5 = { fg = c.pink, },
	rainbowcol6 = { fg = c.cyan, },
	rainbowcol7 = { fg = c.white, },
}
